## ====================================================================
## Makefile for antigravity-cli-ide
## ====================================================================

EMACS ?= emacs
EMACSFLAGS ?= -Q -batch -L .

# Package source files in topological dependency order
SRC = antigravity-cli-ide-debug.el \
      antigravity-cli-ide-diagnostics.el \
      antigravity-cli-ide-emacs-tools.el \
      antigravity-cli-ide-mcp-server.el \
      antigravity-cli-ide-mcp-http-server.el \
      antigravity-cli-ide-mcp-handlers.el \
      antigravity-cli-ide-mcp.el \
      antigravity-cli-ide-transient.el \
      antigravity-cli-ide.el

TESTS = antigravity-cli-ide-tests.el

ELC = $(SRC:.el=.elc)

.PHONY: all compile test clean checkdoc help

all: compile test

compile: $(ELC)

%.elc: %.el
	@echo "Compiling $<..."
	@$(EMACS) $(EMACSFLAGS) -f batch-byte-compile $<

# Module dependencies for reliable parallel builds (-j)
antigravity-cli-ide-diagnostics.elc: antigravity-cli-ide-debug.elc
antigravity-cli-ide-mcp-server.elc: antigravity-cli-ide-debug.elc
antigravity-cli-ide-mcp-http-server.elc: antigravity-cli-ide-debug.elc antigravity-cli-ide-mcp-server.elc
antigravity-cli-ide-mcp-handlers.elc: antigravity-cli-ide-debug.elc antigravity-cli-ide-diagnostics.elc
antigravity-cli-ide-mcp.elc: antigravity-cli-ide-debug.elc antigravity-cli-ide-mcp-handlers.elc antigravity-cli-ide-mcp-server.elc
antigravity-cli-ide-emacs-tools.elc: antigravity-cli-ide-mcp-server.elc
antigravity-cli-ide-transient.elc: antigravity-cli-ide-debug.elc
antigravity-cli-ide.elc: antigravity-cli-ide-debug.elc antigravity-cli-ide-mcp.elc antigravity-cli-ide-transient.elc antigravity-cli-ide-emacs-tools.elc

test:
	@echo "Running ERT automated tests..."
	@$(EMACS) $(EMACSFLAGS) -l ert -l $(TESTS) -f ert-run-tests-batch-and-exit

clean:
	@echo "Cleaning compiled .elc files..."
	@rm -f *.elc

checkdoc:
	@echo "Running checkdoc on source files..."
	@$(EMACS) $(EMACSFLAGS) --eval '(progn \
		(require (quote checkdoc)) \
		(dolist (file (list $(patsubst %,"%",$(SRC)))) \
			(with-current-buffer (find-file-noselect file) \
				(checkdoc-current-buffer t))))'

help:
	@echo "Available targets:"
	@echo "  all       - Byte-compile all source files and run test suite (default)"
	@echo "  compile   - Byte-compile all Emacs Lisp source files"
	@echo "  test      - Run ERT automated test suite in batch mode"
	@echo "  clean     - Remove generated byte-compiled (.elc) files"
	@echo "  checkdoc  - Run checkdoc style inspection on source files"
	@echo "  help      - Show this help message"
